### ISSUE TITLE
Documentation to set up the game

### ISSUE THREAD

**Issue by Shadowsych** [nking1232/Nz-Game#1]
Hello Nathan King,

It would be best if you could explain how we could set the game up. I want to play the game, but I don't have any proper documentation in doing so :cry:

**Comment by nking1232** [comment]
Sorry shadow but I have not added all of the files to the repository yet i'm still undergoing some reorganization. Once i've finished i'll add a code blocks project.

**Comment by Shadowsych** [comment]
Thanks, answers my question!
